name: Build/release

on: 
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        node: [ '12', '10', '8' ]
        include:
        - os: windows-latest
          commandPrefix: ''
        - os: ubuntu-latest
          commandPrefix: xvfb-run

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Build/release Electron app
        run: |
          yarn
          yarn bp