name: Build/release

on: 
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: |
          yarn
          yarn electron:build
        shell: pwsh

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: dist_electron
          path: dist_electron
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}