name: Build/release

on: 
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Get version
        run: |
          PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
          echo $PACKAGE_VERSION
          echo ::set-env name=PACKAGE_VERSION::$PACKAGE_VERSION
        shell: pwsh

      - name: Build/release Electron app
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: |
          yarn
          yarn bp