name: Build/release

on: 
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check & Install
        uses: actions/checkout@v2
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Get version
        run: |
          PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
          echo $PACKAGE_VERSION
          echo ::set-env name=PACKAGE_VERSION::$PACKAGE_VERSION
        shell: pwsh

      - name: Build/release Electron app
        run: |
          npm run bd
        shell: pwsh

      - name: Upload Windows exe
        uses: actions/upload-artifact@v1
        with:
          name: exe
          path: ./dist_electron/ptest.setup.${{env.PACKAGE_VERSION}}.exe

      - name: clean
        run: |
          npm run clean
        shell: pwsh